# Generated by Django 3.2.10 on 2021-12-19 06:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('icon', models.CharField(default='file', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_type', models.CharField(choices=[('DIR', 'Directory'), ('FILE', 'File')], default='FILE', max_length=32)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='objects/')),
                ('privacy_status', models.CharField(choices=[('PVT', 'Private'), ('PUB', 'Public')], default='PVT', max_length=32)),
                ('opened_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rights', models.CharField(choices=[('VIEW', 'Viewer'), ('CMT', 'Commenter'), ('EDIT', 'Editor')], default='VIEW', max_length=32)),
                ('last_invited_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_access_object', to='objects.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_access_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='access_to',
            field=models.ManyToManyField(through='objects.ObjectAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object'),
        ),
        migrations.AddField(
            model_name='object',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.filetype'),
        ),
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
